// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/compiler/Lexer.jflex

// ------------  Paquete e importaciones ------------
package compiler;

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\5\0\1\7\1\10\2\0\1\11\1\12"+
    "\1\13\1\14\12\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\0\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\2\31\1\35\1\36\1\37\1\40"+
    "\1\41\1\31\1\42\1\43\1\44\1\45\1\46\1\31"+
    "\1\47\1\31\1\50\1\51\1\0\1\52\3\0\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\2\31\1\35\1\36\1\37\1\40\1\41\1\31\1\42"+
    "\1\43\1\44\1\45\1\46\1\31\1\47\1\31\1\50"+
    "\12\0\1\3\252\0\2\53\115\0\1\54\u01a8\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\1"+
    "\12\16\1\17\1\20\1\1\1\21\1\0\1\22\2\0"+
    "\1\23\5\16\1\0\6\16\1\0\4\16\1\0\1\10"+
    "\1\0\1\24\3\16\1\25\1\16\1\25\1\26\1\27"+
    "\1\16\1\30\1\31\1\32\1\30\2\16\1\0\2\33"+
    "\1\34\1\35\1\34\1\0\1\36\2\16\1\0\2\16"+
    "\1\0\1\37\2\16\1\0\1\16\1\0\1\21\2\16"+
    "\1\0\1\16\2\40\1\41\1\16\1\41\1\16\1\0"+
    "\1\42\1\16\1\0\1\43\1\16\1\0\2\16\1\0"+
    "\2\44\2\45\1\46\1\16\1\0\2\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\55\0\132\0\207\0\55\0\55\0\55"+
    "\0\55\0\264\0\55\0\55\0\341\0\55\0\55\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276"+
    "\0\u02a3\0\u02d0\0\55\0\55\0\u02fd\0\132\0\207\0\55"+
    "\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de\0\u040b\0\u0438\0\u0465"+
    "\0\u0492\0\u04bf\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd"+
    "\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae\0\u032a\0\u06db\0\u0168"+
    "\0\u0708\0\u0735\0\u0762\0\u0168\0\u078f\0\55\0\u0168\0\u0168"+
    "\0\u07bc\0\u0168\0\u07e9\0\u0168\0\55\0\u0816\0\u0843\0\u0870"+
    "\0\u0168\0\55\0\u0168\0\u089d\0\55\0\u08ca\0\u0168\0\u08f7"+
    "\0\u0924\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u0168\0\u0a05\0\u0a32"+
    "\0\u0a5f\0\u0a8c\0\u0ab9\0\55\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d"+
    "\0\u0b9a\0\u0bc7\0\u0168\0\u0bf4\0\55\0\u0c21\0\u0c4e\0\u0168"+
    "\0\u0c7b\0\u0ca8\0\u0168\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89"+
    "\0\u0168\0\55\0\u0168\0\55\0\u0168\0\u0db6\0\u0de3\0\u0168"+
    "\0\55";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\2\2\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\5\22"+
    "\1\26\2\22\1\27\1\30\1\31\2\22\1\32\2\22"+
    "\1\33\1\34\1\2\1\35\55\0\2\36\1\0\1\36"+
    "\1\0\50\36\2\37\1\0\3\37\1\40\46\37\13\0"+
    "\1\41\1\0\1\12\44\0\1\42\73\0\25\43\21\0"+
    "\1\22\6\0\16\22\1\44\6\22\21\0\1\22\6\0"+
    "\25\22\21\0\1\22\6\0\7\22\1\45\4\22\1\46"+
    "\10\22\21\0\1\22\6\0\10\22\1\47\3\22\1\50"+
    "\10\22\2\0\1\51\16\0\1\22\6\0\13\22\1\52"+
    "\11\22\21\0\1\22\6\0\1\53\3\22\1\54\3\22"+
    "\1\55\3\22\1\56\4\22\1\57\3\22\2\0\1\60"+
    "\16\0\1\22\6\0\16\22\1\61\6\22\21\0\1\22"+
    "\6\0\4\22\1\62\20\22\21\0\1\22\6\0\21\22"+
    "\1\63\3\22\21\0\1\22\6\0\1\64\24\22\51\0"+
    "\1\65\24\0\1\66\37\0\14\67\1\0\40\67\15\0"+
    "\1\43\6\0\25\43\21\0\1\22\6\0\16\22\1\70"+
    "\6\22\21\0\1\22\6\0\1\71\24\22\21\0\1\22"+
    "\6\0\11\22\1\72\1\22\1\73\11\22\21\0\1\22"+
    "\6\0\22\22\1\74\2\22\21\0\1\22\6\0\21\22"+
    "\1\75\3\22\52\0\1\76\23\0\1\22\6\0\3\22"+
    "\1\77\21\22\21\0\1\22\6\0\23\22\1\100\1\22"+
    "\21\0\1\22\6\0\3\22\1\101\21\22\21\0\1\22"+
    "\6\0\13\22\1\102\11\22\21\0\1\22\6\0\3\22"+
    "\1\103\21\22\21\0\1\22\6\0\11\22\1\104\13\22"+
    "\43\0\1\105\32\0\1\22\6\0\10\22\1\106\3\22"+
    "\1\107\10\22\2\0\1\110\16\0\1\22\6\0\17\22"+
    "\1\111\5\22\3\0\1\112\15\0\1\22\6\0\12\22"+
    "\1\113\12\22\21\0\1\22\6\0\16\22\1\114\6\22"+
    "\42\0\1\115\16\0\5\67\1\116\47\67\15\0\1\22"+
    "\6\0\16\22\1\117\6\22\21\0\1\22\6\0\21\22"+
    "\1\120\3\22\21\0\1\22\6\0\17\22\1\121\5\22"+
    "\3\0\1\122\15\0\1\22\6\0\1\22\1\123\23\22"+
    "\21\0\1\22\6\0\10\22\1\124\14\22\2\0\1\125"+
    "\16\0\1\22\6\0\1\126\24\22\21\0\1\22\6\0"+
    "\13\22\1\127\11\22\21\0\1\22\6\0\6\22\1\130"+
    "\16\22\43\0\1\131\32\0\1\22\6\0\10\22\1\132"+
    "\14\22\2\0\1\133\1\0\5\67\1\116\14\67\1\134"+
    "\32\67\15\0\1\22\6\0\12\22\1\135\12\22\21\0"+
    "\1\22\6\0\14\22\1\136\10\22\44\0\1\137\31\0"+
    "\1\22\6\0\11\22\1\140\13\22\21\0\1\22\6\0"+
    "\1\141\24\22\30\0\1\142\45\0\1\22\6\0\20\22"+
    "\1\143\4\22\21\0\1\22\6\0\16\22\1\144\6\22"+
    "\50\0\1\145\25\0\1\22\6\0\1\146\24\22\30\0"+
    "\1\147\45\0\1\22\6\0\13\22\1\150\11\22\21\0"+
    "\1\22\6\0\11\22\1\151\13\22\41\0\1\152\34\0"+
    "\1\22\6\0\4\22\1\153\20\22\21\0\1\22\6\0"+
    "\13\22\1\154\11\22\43\0\1\155\32\0\1\22\6\0"+
    "\1\156\24\22\21\0\1\22\6\0\13\22\1\157\11\22"+
    "\43\0\1\160\32\0\1\22\6\0\4\22\1\161\20\22"+
    "\34\0\1\162\41\0\1\22\6\0\1\163\24\22\30\0"+
    "\1\164\45\0\1\22\6\0\12\22\1\165\12\22\21\0"+
    "\1\22\6\0\24\22\1\166\54\0\1\167\21\0\1\22"+
    "\6\0\1\170\24\22\30\0\1\171\30\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3600];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\4\11\1\1\2\11\1\1\2\11"+
    "\13\1\2\11\2\1\1\0\1\11\2\0\6\1\1\0"+
    "\6\1\1\0\4\1\1\0\1\1\1\0\6\1\1\11"+
    "\6\1\1\11\2\1\1\0\1\1\1\11\2\1\1\11"+
    "\1\0\3\1\1\0\2\1\1\0\3\1\1\0\1\1"+
    "\1\0\1\11\2\1\1\0\5\1\1\11\1\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\1\1\1\11"+
    "\1\1\1\11\2\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { main.Main.listaErrores.add(new utilities.ErrorClass("Léxico", yytext(), yyline, yycolumn));
//                System.out.println("Error Lexico: " + yytext() + " | Fila:" + yyline + " | Columna: " + yycolumn);
            }
          // fall through
          case 40: break;
          case 2:
            { /* Espacios en blanco se ignoran */
            }
          // fall through
          case 41: break;
          case 3:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.EXCL, yycolumn, yyline, yytext());
            }
          // fall through
          case 42: break;
          case 4:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.PARIZQ, yycolumn, yyline, yytext());
            }
          // fall through
          case 43: break;
          case 5:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.PARDER, yycolumn, yyline, yytext());
            }
          // fall through
          case 44: break;
          case 6:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.COMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 45: break;
          case 7:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.MENOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 46: break;
          case 8:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Double", yyline, yycolumn));
    return new Symbol(sym.DOUBLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 47: break;
          case 9:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.DOSPUNTOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 48: break;
          case 10:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.PYC, yycolumn, yyline, yytext());
            }
          // fall through
          case 49: break;
          case 11:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.MENOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 50: break;
          case 12:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 51: break;
          case 13:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.MAYOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 52: break;
          case 14:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Id", yyline, yycolumn));
    return new Symbol(sym.ID, yycolumn, yyline, yytext());
            }
          // fall through
          case 53: break;
          case 15:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.CORCHIZQ, yycolumn, yyline, yytext());
            }
          // fall through
          case 54: break;
          case 16:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Simbolo", yyline, yycolumn));
    return new Symbol(sym.CORCHDER, yycolumn, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 17:
            { 
            }
          // fall through
          case 56: break;
          case 18:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Char", yyline, yycolumn));
    return new Symbol(sym.CADENA, yycolumn, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 19:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Id Array", yyline, yycolumn));
    return new Symbol(sym.IDARRAY, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 20:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RARRAY, yycolumn, yyline, yytext());
            }
          // fall through
          case 59: break;
          case 21:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RDIV, yycolumn, yyline, yytext());
            }
          // fall through
          case 60: break;
          case 22:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.REND, yycolumn, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 23:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RMAX, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 24:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RMIN, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 25:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RMOD, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 26:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RMUL, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 27:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RRES, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 28:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RSUM, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 29:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RVAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 30:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RCHAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 31:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RMODA, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 32:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RMEDIA, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 33:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RPRINT, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 34:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RCOLUMN, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 35:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RDOUBLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 36:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RCONSOLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 37:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RMEDIANA, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 38:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RPROGRAM, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 39:
            { main.Main.listaTokens.add(new utilities.Token(yytext() ,"Palabra Reservada", yyline, yycolumn));
    return new Symbol(sym.RVARIANZA, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
