
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 25;
  public static final int RDIV = 8;
  public static final int RMIN = 15;
  public static final int ENTERO = 34;
  public static final int RMODA = 12;
  public static final int RMEDIA = 10;
  public static final int RMUL = 7;
  public static final int RMOD = 9;
  public static final int RPRINT = 16;
  public static final int CORCHIZQ = 22;
  public static final int IGUAL = 30;
  public static final int ARROBA = 27;
  public static final int RCONSOLE = 17;
  public static final int EXCL = 18;
  public static final int EOF = 0;
  public static final int PARIZQ = 20;
  public static final int REND = 3;
  public static final int RSUM = 6;
  public static final int COMILLAS = 28;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int CADENA = 35;
  public static final int MENOS = 29;
  public static final int MENOR = 31;
  public static final int RMAX = 14;
  public static final int RVAR = 4;
  public static final int MAYOR = 32;
  public static final int PUNTO = 26;
  public static final int CORCHDER = 23;
  public static final int RVARIANZA = 13;
  public static final int IGUALIGUAL = 33;
  public static final int RRES = 5;
  public static final int PARDER = 19;
  public static final int RMEDIANA = 11;
  public static final int RPROGRAM = 2;
  public static final int PYC = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RPROGRAM",
  "REND",
  "RVAR",
  "RRES",
  "RSUM",
  "RMUL",
  "RDIV",
  "RMOD",
  "RMEDIA",
  "RMEDIANA",
  "RMODA",
  "RVARIANZA",
  "RMAX",
  "RMIN",
  "RPRINT",
  "RCONSOLE",
  "EXCL",
  "PARDER",
  "PARIZQ",
  "PYC",
  "CORCHIZQ",
  "CORCHDER",
  "COMA",
  "DOSPUNTOS",
  "PUNTO",
  "ARROBA",
  "COMILLAS",
  "MENOS",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "IGUALIGUAL",
  "ENTERO",
  "CADENA"
  };
}

